#ifndef PIXMAN_INTERFACE_DEF_H
#define PIXMAN_INTERFACE_DEF_H
/*
** This file is machine generated from idltool
** Do not edit
*/ 

#include <exec/types.i>
#include <exec/exec.i>
#include <exec/interfaces.i>

STRUCTURE PixmanIFace, InterfaceData_SIZE
	    FPTR IPixman_pixman_transform_init_identity
	    FPTR IPixman_pixman_transform_point_3d
	    FPTR IPixman_pixman_transform_point
	    FPTR IPixman_pixman_transform_multiply
	    FPTR IPixman_pixman_transform_init_scale
	    FPTR IPixman_pixman_transform_scale
	    FPTR IPixman_pixman_transform_init_rotate
	    FPTR IPixman_pixman_transform_rotate
	    FPTR IPixman_pixman_transform_init_translate
	    FPTR IPixman_pixman_transform_translate
	    FPTR IPixman_pixman_transform_bounds
	    FPTR IPixman_pixman_transform_invert
	    FPTR IPixman_pixman_transform_is_identity
	    FPTR IPixman_pixman_transform_is_scale
	    FPTR IPixman_pixman_transform_is_int_translate
	    FPTR IPixman_pixman_transform_is_inverse
	    FPTR IPixman_pixman_transform_from_pixman_f_transform
	    FPTR IPixman_pixman_f_transform_from_pixman_transform
	    FPTR IPixman_pixman_f_transform_invert
	    FPTR IPixman_pixman_f_transform_point
	    FPTR IPixman_pixman_f_transform_point_3d
	    FPTR IPixman_pixman_f_transform_multiply
	    FPTR IPixman_pixman_f_transform_init_scale
	    FPTR IPixman_pixman_f_transform_scale
	    FPTR IPixman_pixman_f_transform_init_rotate
	    FPTR IPixman_pixman_f_transform_rotate
	    FPTR IPixman_pixman_f_transform_init_translate
	    FPTR IPixman_pixman_f_transform_translate
	    FPTR IPixman_pixman_f_transform_bounds
	    FPTR IPixman_pixman_f_transform_init_identity
	    FPTR IPixman_pixman_region_set_static_pointers
	    FPTR IPixman_pixman_region_init
	    FPTR IPixman_pixman_region_init_rect
	    FPTR IPixman_pixman_region_init_rects
	    FPTR IPixman_pixman_region_init_with_extents
	    FPTR IPixman_pixman_region_init_from_image
	    FPTR IPixman_pixman_region_fini
	    FPTR IPixman_pixman_region_translate
	    FPTR IPixman_pixman_region_copy
	    FPTR IPixman_pixman_region_intersect
	    FPTR IPixman_pixman_region_union
	    FPTR IPixman_pixman_region_union_rect
	    FPTR IPixman_pixman_region_intersect_rect
	    FPTR IPixman_pixman_region_subtract
	    FPTR IPixman_pixman_region_inverse
	    FPTR IPixman_pixman_region_contains_point
	    FPTR IPixman_pixman_region_contains_rectangle
	    FPTR IPixman_pixman_region_not_empty
	    FPTR IPixman_pixman_region_extents
	    FPTR IPixman_pixman_region_n_rects
	    FPTR IPixman_pixman_region_rectangles
	    FPTR IPixman_pixman_region_equal
	    FPTR IPixman_pixman_region_selfcheck
	    FPTR IPixman_pixman_region_reset
	    FPTR IPixman_pixman_region_clear
	    FPTR IPixman_pixman_region32_init
	    FPTR IPixman_pixman_region32_init_rect
	    FPTR IPixman_pixman_region32_init_rects
	    FPTR IPixman_pixman_region32_init_with_extents
	    FPTR IPixman_pixman_region32_init_from_image
	    FPTR IPixman_pixman_region32_fini
	    FPTR IPixman_pixman_region32_translate
	    FPTR IPixman_pixman_region32_copy
	    FPTR IPixman_pixman_region32_intersect
	    FPTR IPixman_pixman_region32_union
	    FPTR IPixman_pixman_region32_intersect_rect
	    FPTR IPixman_pixman_region32_union_rect
	    FPTR IPixman_pixman_region32_subtract
	    FPTR IPixman_pixman_region32_inverse
	    FPTR IPixman_pixman_region32_contains_point
	    FPTR IPixman_pixman_region32_contains_rectangle
	    FPTR IPixman_pixman_region32_not_empty
	    FPTR IPixman_pixman_region32_extents
	    FPTR IPixman_pixman_region32_n_rects
	    FPTR IPixman_pixman_region32_rectangles
	    FPTR IPixman_pixman_region32_equal
	    FPTR IPixman_pixman_region32_selfcheck
	    FPTR IPixman_pixman_region32_reset
	    FPTR IPixman_pixman_region32_clear
	    FPTR IPixman_pixman_blt
	    FPTR IPixman_pixman_fill
	    FPTR IPixman_pixman_version
	    FPTR IPixman_pixman_version_string
	    FPTR IPixman_pixman_format_supported_destination
	    FPTR IPixman_pixman_format_supported_source
	    FPTR IPixman_pixman_image_create_solid_fill
	    FPTR IPixman_pixman_image_create_linear_gradient
	    FPTR IPixman_pixman_image_create_radial_gradient
	    FPTR IPixman_pixman_image_create_conical_gradient
	    FPTR IPixman_pixman_image_create_bits
	    FPTR IPixman_pixman_image_ref
	    FPTR IPixman_pixman_image_unref
	    FPTR IPixman_pixman_image_set_destroy_function
	    FPTR IPixman_pixman_image_get_destroy_data
	    FPTR IPixman_pixman_image_set_clip_region
	    FPTR IPixman_pixman_image_set_clip_region32
	    FPTR IPixman_pixman_image_set_has_client_clip
	    FPTR IPixman_pixman_image_set_transform
	    FPTR IPixman_pixman_image_set_repeat
	    FPTR IPixman_pixman_image_set_filter
	    FPTR IPixman_pixman_image_set_source_clipping
	    FPTR IPixman_pixman_image_set_alpha_map
	    FPTR IPixman_pixman_image_set_component_alpha
	    FPTR IPixman_pixman_image_get_component_alpha
	    FPTR IPixman_pixman_image_set_accessors
	    FPTR IPixman_pixman_image_set_indexed
	    FPTR IPixman_pixman_image_get_data
	    FPTR IPixman_pixman_image_get_width
	    FPTR IPixman_pixman_image_get_height
	    FPTR IPixman_pixman_image_get_stride
	    FPTR IPixman_pixman_image_get_depth
	    FPTR IPixman_pixman_image_get_format
	    FPTR IPixman_pixman_image_fill_rectangles
	    FPTR IPixman_pixman_image_fill_boxes
	    FPTR IPixman_pixman_compute_composite_region
	    FPTR IPixman_pixman_image_composite
	    FPTR IPixman_pixman_image_composite32
	    FPTR IPixman_pixman_disable_out_of_bounds_workaround
	    FPTR IPixman_pixman_glyph_cache_create
	    FPTR IPixman_pixman_glyph_cache_destroy
	    FPTR IPixman_pixman_glyph_cache_freeze
	    FPTR IPixman_pixman_glyph_cache_thaw
	    FPTR IPixman_pixman_glyph_cache_lookup
	    FPTR IPixman_pixman_glyph_cache_insert
	    FPTR IPixman_pixman_glyph_cache_remove
	    FPTR IPixman_pixman_glyph_get_extents
	    FPTR IPixman_pixman_glyph_get_mask_format
	    FPTR IPixman_pixman_composite_glyphs
	    FPTR IPixman_pixman_composite_glyphs_no_mask
	    FPTR IPixman_pixman_sample_ceil_y
	    FPTR IPixman_pixman_sample_floor_y
	    FPTR IPixman_pixman_edge_step
	    FPTR IPixman_pixman_edge_init
	    FPTR IPixman_pixman_line_fixed_edge_init
	    FPTR IPixman_pixman_rasterize_edges
	    FPTR IPixman_pixman_add_traps
	    FPTR IPixman_pixman_add_trapezoids
	    FPTR IPixman_pixman_rasterize_trapezoid
	    FPTR IPixman_pixman_composite_trapezoids
	    FPTR IPixman_pixman_composite_triangles
	    FPTR IPixman_pixman_add_triangles
	LABEL PixmanIFace_SIZE

#endif
