#ifndef INLINE4_PIXMAN_H
#define INLINE4_PIXMAN_H

/*
** This file was auto generated by idltool 53.5.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef PIXMAN_H
#include <pixman.h>
#endif
#include <interfaces/pixman.h>

/* No inline4 macros are defined here. */

#endif /* INLINE4_PIXMAN_H */
