default: all

top_srcdir = ..
include $(top_srcdir)/pixman/Makefile.sources
include $(top_srcdir)/Makefile.amiga.common

OBJECTS = $(patsubst %.c, %.o, $(libpixman_sources))

CFLAGS = -O2 -mhard-float -I$(top_srcdir)/amiga $(AMIGA_CFLAGS)
CC = ppc-amigaos-gcc
PERL = perl

# targets
all:  libpixman.a

# pixman linking
libpixman.a: pixman-combine32.h pixman-combine64.h $(OBJECTS)
	ppc-amigaos-ar rcs libpixman.a $(OBJECTS)

.PHONY: clean
clean:
	rm -Rf $(OBJECTS) libpixman.a
